Dev
lehahel/distance_learning_simulator pull request #1
Opened 2020-05-14 09:55 UTC by lehahel

Алексей Попов 924

2020-05-17 21:32 UTC, WokinShopash requested changes

2020-05-17 21:32 UTC, WokinShopash commented on review_2/launch_client.py
> +        tkinter.Label(self.root, width=20, textvariable=self.energy_text, borderwidth=2, relief="groove").grid(row=1,
Стоит какой-нибудь циклик тут сделать, чтобы покомпактнее было.

2020-05-17 21:32 UTC, WokinShopash commented on review_2/launch_client.py
> +        self.energy_text.set("Energy: " + params[1])
Да, точно цикл напрашивается.
Положить эти кнопки/тексты рядышком, обернуть в классы, возможно.

2020-05-17 21:32 UTC, WokinShopash commented on review_2/launch_server.py
> +    return student.name + '\n' + str(student.energy) + '\n' + str(student.fat) \
'\n'.join же

2020-05-17 21:32 UTC, WokinShopash commented on review_2/launch_server.py
> +        self.ip = "localhost"
Тут не хватает комментария, что это дефолты и настоящие значения спрашиваются, а то можно подумать, что это хардкод

2020-05-17 21:32 UTC, WokinShopash commented on review_2/server/checker.py
> +def check_ip(ip):
Что это у нас тут, гражданин? Дублирование кода?
Т.к. код общий в клиенте и сервере, нужно создать общую либу (папочку на том же уровне, что server и client)

2020-05-17 21:32 UTC, WokinShopash commented on review_2/server/lib.py
> +        if self.energy < min_stat_limits["energy"]:
лучше, чуть компактнее эти штуки сделать:
`self.energy = max(self.energy, min_stat_limits["energy"])`
А можно и верхний лимит туда же вписать, вообще в одну строку будет, но это может смотреться громоздко, тут уже сам смотри, как эстетически больше нравится.

2020-05-21 17:38 UTC, WokinShopash requested changes
1. Убери из репозитория __pychache__-папки
2. Нужно корректно обработать ситуацию, когда сервер не запущен или нет сети

2020-05-21 17:38 UTC, WokinShopash commented on client/studlib.py
> +import tkinter
не используется

2020-05-21 17:38 UTC, WokinShopash commented on server/lib.py
> +interrupted_sleep_reasons = [
Я бы вот эти константы унес в текстовый конфигурационный файлик

2020-05-21 17:38 UTC, WokinShopash commented on server/lib.py
> +    def study(self):
Тут и в следующей функции тоже многовато констант, которые бы в конфиг унести

2020-05-21 17:38 UTC, WokinShopash commented on launch_test.py
> +        student.eat(food)
А с циклом на строчку меньше будет

2020-05-21 17:38 UTC, WokinShopash commented on launch_client.py
> +handlers = {
Тексты тоже в конфиг уносим

2020-05-21 17:38 UTC, WokinShopash commented on review_2/launch_server.py
> +        self.ip = "localhost"
Кажется, не исправлено

2020-05-24 14:30 UTC, lehahel commented on server/lib.py
> +    def study(self):
Они плодят еще больше строк, чем было;(

2020-05-24 23:19 UTC, WokinShopash approved these changes
Зачет +1 допбалл

2020-12-03 14:40 UTC, merged